name: Crowdin Action

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: crowdin action
      uses: crowdin/github-action@1.4.9
      with:
        upload_translations: false
        download_translations: true
	download_language: 'en,de,fr,it,nl,ru,fi,es'
	localization_branch_name: l10n_crowdin_action
    	create_pull_request: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_API_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.OH_CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.OH_CROWDIN_ACCOUNT_KEY }
