name: Crowdin Action

on:
  workflow_dispatch:

jobs:
  synchronize-with-crowdin:
    runs-on: macos-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: crowdin action
      uses: crowdin/github-action@1.4.9
      with:
        upload_translations: false
        download_translations: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_API_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.OH_CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.OH_CROWDIN_ACCOUNT_KEY }
