# This is a basic workflow that is manually triggered

name: GitHub Release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_deploy::
    runs-on: macos-13

    steps:
    - name: Deploy on TestFlight
        env:
          LANG: en_US.UTF-8
          LC_ALL: en_US.UTF-8
          FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 60
        uses: maierj/fastlane-action@v2.2.1
        with:
          lane: set_github_release
